spring:
  datasource:
    username: root
    password: "@Wem71055017"
#    password: 123456
    url: jdbc:mysql://localhost:3306/inventory_assistant?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      min-idle: 50
      max-active: 500
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: top.tzdian.blogserver.pojo
  config-location: classpath:/mybatis/mybatis-config.xml

server:
  port: 8888
  servlet:
    context-path: /assistant

logging:
  file:
    name: log/log.log
  level:
    root: info
    top:
      tzdian:
        blogserver: debug